language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install flake8 pytest coverage "pytest-cov<2.6.0" codacy-coverage
# command to run tests
script:
  - python3 -m flake8
  - python3 -m pytest --cov=cayennelpp
  - python3 -m coverage xml
  - python3 -m codacy -r coverage.xml
  - test -z "$(git log -E --grep='^(Merge|chore|docs|feat|fix|refactor|style|test)' --invert-grep)"
