language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install flake8 pytest coverage
# preparce codacy coverage report
before_script:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) download
# command to run tests
script:
  - test -z "$(git log -E --grep='^(Merge|((chore|docs|feat|fix|refactor|style|tests)\:))' --invert-grep)"
  - python3 -m flake8 cayennelpp
  - python3 -m pytest
  - python3 -m coverage run -m pytest
  - python3 -m coverage xml
# upload codacy results
after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
